export const APPARTMENT_REQUEST = "APPARTMENT_REQUEST";
export const APPARTMENT_SUCCESS = "APPARTMENT_SUCCESS";
export const APPARTMENT_FAIL = "APPARTMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
