export const ALL_SWITCH_REQUEST = "ALL_SWITCH_REQUEST";
export const ALL_SWITCH_SUCCESS = "ALL_SWITCH_SUCCESS";
export const ALL_SWITCH_FAIL = "ALL_SWITCH_FAIL";

export const SINGLE_SWITCH_REQUEST = "SINGLE_SWITCH_REQUEST";
export const SINGLE_SWITCH_SUCCESS = "SINGLE_SWITCH_SUCCESS";
export const SINGLE_SWITCH_FAIL = "SINGLE_SWITCH_FAIL";

export const CREATE_SWITCH_REQUEST = "CREATE_SWITCH_REQUEST";
export const CREATE_SWITCH_SUCCESS = "CREATE_SWITCH_SUCCESS";
export const CREATE_SWITCH_FAIL = "CREATE_SWITCH_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
